### PR TITLE
S3 bucket Cloud Formation Syntax

### PR DESCRIPTION
**Pull request by neilramsay**
CloudFormation S3 Bucket and S3 Bucket Policy from:
* http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
* http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html

### CODE REVIEW

**Comment by beaknit** [comment]
PR's 10 & 11 look right to me but I'm not in front of my machine to test them. I'll take a look tomorrow

**Comment by neilramsay** [comment]
PR11 is currently missing "AWS::Route53::HealthCheck".
I will add that in later.

NR

**Comment by beaknit** [comment]
Could you split this into two snippets?

**Comment by neilramsay** [comment]
Yes,
I have been doing two snippets with the first containing both, and the second containing the *policy only.
Is that sufficient?

NR

**Comment by beaknit** [comment]
Since either can be used without the other, I'd rather keep them separate entirely.

**Comment by neilramsay** [comment]
I think it is ready now.
Please review.

NR

**Comment by beaknit** [comment]
LGTM

**Pull request merged**
